# Generated by Django 5.0.7 on 2024-08-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_streamer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
